=== jiekang/thermostat-agent/plugins/vm-gc/agent/src/main/resources/com/redhat/thermostat/vm/gc/agent/gc-params-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

 Copyright 2012-2015 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<xs:schema xmlns="http://icedtea.classpath.org/thermostat/gc-params-mapping/v1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://icedtea.classpath.org/thermostat/gc-params-mapping/v1.0"
           elementFormDefault="qualified">

  <xs:element name="version" type="xs:string"/>
  <xs:element name="common-name" type="xs:string"/>
  <xs:element name="collector-name" type="xs:string"/>
  <xs:element name="flag" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="url" type="xs:string"/>

  <xs:element name="gc-params-mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="common" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="collector" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="common">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gc-params" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="collector">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collector-info"/>
        <xs:element ref="gc-params"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="collector-info">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version"/>
        <xs:element ref="common-name"/>
        <xs:element ref="collector-distinct-names"/>
        <xs:element ref="url"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="collector-distinct-names">
    <xs:annotation>
      <xs:documentation>See GcCommonNameMapper.java
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collector-name" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gc-params">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gc-param" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gc-param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="flag"/>
        <xs:element ref="description"/>
        <xs:element ref="version" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jiekang/thermostat-agent/plugins/vm-gc/agent/src/main/resources/com/redhat/thermostat/vm/gc/agent/gc-params-mapping.xml
<?xml version="1.0"?>
<!--

 Copyright 2012-2017 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<gc-params-mapping xmlns="http://icedtea.classpath.org/thermostat/gc-params-mapping/v1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://icedtea.classpath.org/thermostat/gc-params-mapping/v1.0 gc-params-mapping.xsd">

  <!-- Reference documentation -->
  <!-- http://www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html -->
  <!-- http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/G1GettingStarted/index.html -->
  <!-- http://www.slideshare.net/SimoneBordet/g1-garbage-collector-details-and-tuning -->
  <!-- http://www.oracle.com/technetwork/articles/java/g1gc-1984535.html -->
  <!-- http://icedtea.classpath.org/hg/icedtea7-forest/hotspot/file/aea5b566bfab/src/share/vm/gc_implementation/g1/g1_globals.hpp -->

  <common>
    <gc-params>
      <gc-param>
        <flag>PrintGC</flag>
        <description>Print messages when garbage collection takes place</description>
      </gc-param>
      <gc-param>
        <flag>PrintGCDetails</flag>
        <description>Print more details in garbage collection messages</description>
      </gc-param>
      <gc-param>
        <flag>PrintGCTimeStamps</flag>
        <description>Print timestamps in garbage collection messages</description>
      </gc-param>
      <gc-param>
        <flag>UseGCLogFileRotation</flag>
        <description>Enable GC log file rotation. Requires -Xloggc:filename, which enables logging GC messages to
          file
        </description>
      </gc-param>
      <gc-param>
        <flag>NumberOfGClogFiles</flag>
        <description>The number of rotating log files to use. Must be greater than or equal to 1. The default is 1.
        </description>
      </gc-param>
      <gc-param>
        <flag>GCLogFileSize</flag>
        <description>The maximum log file size in bytes after which the log files will be rotated. Must be greater
          than or equal to 8K. The default is 8K.
        </description>
      </gc-param>
    </gc-params>
  </common>

  <collector>
    <collector-info>
      <version>[1.4.2.0,]</version>
      <common-name>Serial Collector</common-name>
      <collector-distinct-names>
        <collector-name>MSC</collector-name>
        <collector-name>Copy</collector-name>
      </collector-distinct-names>
      <url>http://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html#available_collectors</url>
    </collector-info>
    <gc-params>
      <gc-param>
        <flag>UseSerialGC</flag>
        <description>Use serial garbage collection</description>
      </gc-param>
      <gc-param>
        <flag>ScavengeBeforeFullGC</flag>
        <description>Do garbage collection on young generations before performing full GC cycles</description>
      </gc-param>
      <gc-param>
        <flag>UseGCOverheadLimit</flag>
        <description>Limit the proportion of time that the VM will spend in garbage collection before an OutOfMemory
          error is thrown
        </description>
        <version>[1.6.0.0,]</version>
      </gc-param>
      <gc-param>
        <flag>MaxHeapFreeRatio</flag>
        <description>The maximum percentage of heap size free after a garbage collection cycle to avoid heap
          shrinking. The default is 70
        </description>
      </gc-param>
      <gc-param>
        <flag>MinHeapFreeRatio</flag>
        <description>The minimum percentage of heap size free after a garbage collection cycle to avoid heap
          expansion. The default is 40
        </description>
      </gc-param>
      <gc-param>
        <flag>MaxNewSize</flag>
        <description>The maximum size of the new generation, in bytes. Since 1.4, this is computed as a function of
          NewRatio
        </description>
      </gc-param>
      <gc-param>
        <flag>MaxPermSize</flag>
        <description>The maximum size of the permanent generation, in bytes. Since 5.0, 64-bit VMs are scaled 30%
          larger
        </description>
        <version>[1.4.2.0,1.8.0.0)</version>
      </gc-param>
      <gc-param>
        <flag>NewRatio</flag>
        <description>Ratio of old and new generation sizes. The default is 2</description>
      </gc-param>
      <gc-param>
        <flag>NewSize</flag>
        <description>The default size of the new generation, in bytes. Since 5.0, 64-bit VMs are scaled 30% larger
        </description>
      </gc-param>
      <gc-param>
        <flag>SurvivorRatio</flag>
        <description>Ratio of eden and survivor space. The default is 8</description>
      </gc-param>
      <gc-param>
        <flag>TargetSurvivorRatio</flag>
        <description>The target percentage of survivor space in use after a scavenge</description>
      </gc-param>
    </gc-params>
  </collector>

  <collector>
    <collector-info>
      <version>[1.6.0.14,]</version>
      <common-name>Garbage-First Collector (G1)</common-name>
      <collector-distinct-names>
        <collector-name>G1 incremental collections</collector-name>
      </collector-distinct-names>
      <url>http://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html#available_collectors</url>
    </collector-info>
    <gc-params>
      <gc-param>
        <flag>UseG1GC</flag>
        <description>use the G1 Garbage Collector</description>
      </gc-param>
      <gc-param>
        <flag>MaxGCPauseMillis</flag>
        <description>the max GC pause time goal in milliseconds that G1 will attempt to meet. The default is 200
        </description>
      </gc-param>
      <gc-param>
        <flag>InitiatingHeapOccupancyParent</flag>
        <description>percentage of total heap occupancy at which a GC cycle will be triggered. The default is 45
        </description>
      </gc-param>
      <gc-param>
        <flag>GCPauseIntervalMillis</flag>
        <description>the time interval over which GC pauses totaling up to MaxGCPauseMillis may take place</description>
      </gc-param>
      <gc-param>
        <flag>NewRatio</flag>
        <description>ratio of old a new generation sizes. The default is 2</description>
      </gc-param>
      <gc-param>
        <flag>SurvivorRatio</flag>
        <description>Ratio of eden and survivor space. The default is 8</description>
      </gc-param>
      <gc-param>
        <flag>MaxTenuringThreshold</flag>
        <description>Maximum value for threshold of object tenuring. The default is 15</description>
      </gc-param>
      <gc-param>
        <flag>MaxNewSize</flag>
        <description>The maximum size of the new generation, in bytes. Since 1.4, this is computed as a function of
          NewRatio
        </description>
      </gc-param>
      <gc-param>
        <flag>MaxPermSize</flag>
        <description>The maximum size of the permanent generation, in bytes. Since 5.0, 64-bit VMs are scaled 30%
          larger
        </description>
        <version>[1.6.0.14,1.8.0.0)</version>
      </gc-param>
      <gc-param>
        <flag>ParallelGCThreads</flag>
        <description>The number of threads to use during the parallel phase of GC</description>
      </gc-param>
      <gc-param>
        <flag>ConcGCThreads</flag>
        <description>The number of concurrent GC threads to use</description>
      </gc-param>
      <gc-param>
        <flag>UseGCOverheadLimit</flag>
        <description>Limit the proportion of time that the VM will spend in garbage collection before an OutOfMemory
          error is thrown
        </description>
      </gc-param>
      <gc-param>
        <flag>ScavengeBeforeFullGC</flag>
        <description>Do garbage collection on young generations before performing full GC cycles</description>
      </gc-param>
      <gc-param>
        <flag>MaxHeapFreeRatio</flag>
        <description>The maximum percentage of heap size free after a garbage collection cycle to avoid heap
          shrinking. The default is 70
        </description>
      </gc-param>
      <gc-param>
        <flag>MinHeapFreeRatio</flag>
        <description>The minimum percentage of heap size free after a garbage collection cycle to avoid heap
          expansion. The default is 40
        </description>
      </gc-param>
      <gc-param>
        <flag>NewSize</flag>
        <description>The default size of the new generation, in bytes. Since 5.0, 64-bit VMs are scaled 30%
          larger
        </description>
      </gc-param>
      <gc-param>
